### ISSUE TITLE
auro-flightline: Distorted Flight Line

### ISSUE THREAD

**Issue by ggrewal108** [AlaskaAirlines/auro-flightline#55]
## Describe the bug
The flight changes team is working on sorting sorting flight options within our react microsite and we occasionally see the flight line either disappear - whenever the flight has one segment - or see it distorted - when there are more than one segments. 

## To Reproduce
We have not noticed this behavior on initial load of our page, however, when we try to sort the flight options displayed on the screen, we see this behavior. When the sorting is triggered within our react app, the flight results are sorted and dispatched to the state again which causes a re-rendering of the options on the page.

## Expected behavior
Once the results are sorted, we expected the flight line to be rendered as usual without any distortion.

## Screenshots
<img width="626" alt="Screenshot 2023-07-12 at 1 01 52 PM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/107504325/ce510a49-f0c1-40a5-bd82-472713428731">
<img width="615" alt="Screenshot 2023-07-12 at 1 02 03 PM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/107504325/8a18f319-8629-4f3d-8e27-1094adb889d9">

## Desktop (please complete the following information):
 - OS: [e.g. iOS] : Mac
 - Browser [e.g. chrome, safari] : noticed both on chrome and safari
 - Version [e.g. 22] : Safari = Version 16.5.1 and Chrome = Version 114.0.5735.198

## Smartphone (please complete the following information):
Did not directly test the issue on a smartphone, however tried responsive design mode under the develop menu on safari and the issue was seen again.

## Additional context
N/A

**Comment by blackfalcon** [comment]
Can you provide us with a reproducible test environment to troubleshoot this? As of right now, we have no way of reproducing this behavior.

**Comment by fajar-apri-alaska** [comment]
For the the one that are disappearing, I assume that when we put an empty `flightline` component (without the segment) inside `flex`-based div, it needs  a `width: 100%` so that it renders.

This one does render:
```
<div style="flex">
  <span> Left text </span>
  <auro-flightline style={{width: '100%'}}></auro-flightline>
  <span> Right text </span>
</div>
```
<img width="1440" alt="image" src="https://github.com/AlaskaAirlines/auro-flightline/assets/124668226/5c2e61e0-7493-4311-bd9d-8228471cc288">

This one doesn't:
```
<div style="flex">
  <span> Left text </span>
  <auro-flightline></auro-flightline>
  <span> Right text </span>
</div>
```
<img width="1440" alt="image" src="https://github.com/AlaskaAirlines/auro-flightline/assets/124668226/215cecf3-f9fd-485f-9edd-7d4711a34cbd">

**Comment by ggrewal108** [comment]
> Can you provide us with a reproducible test environment to troubleshoot this? As of right now, we have no way of reproducing this behavior.

Sorry for the slightly late reply. If you would like to see this behavior in action, you should be able to use switch hosts and toggle the TEST environment. Then navigate to the Manage/View PNR page using a one way domestic PNR and then navigate to the reissue start page. Once you are there make sure that the toggle for 'Available Flights Beta' is on (towards the bottom of the page) and click continue. That should take you to the new available flights page where you should be able to toggle sorting options and see the behavior. Let me know if you need anything else.

**Comment by blackfalcon** [comment]
I am still unable to repro this issue? Give the initial description, I cannot repor this issue with a very similar example on the Auro docsite https://auro.alaskaair.com/components/auro/flight#:~:text=auro%2Dflight%3E-,Mainline,-%2B%20mainline%20connection%20w

@fajar-apri-alaska I am unable to repro your version either. Given your hypothesis, why is this not appearing on the Flight demo page?

**Comment by fajar-apri-alaska** [comment]
I think the auro-flight demo page / instruction should have no problem.

While I don't know how the devs implement the auro-flight/auro-flightline component, I did found the issue occurs when the code is implemented outside of the given instructions (for example, wrapping the `auro-flightline` elements with a div according to what I found).

Things that I got for the 'distorted' issue to be reproduced like above example:

1. There are multiple `auro-flightline` elements
2. The container of those `auro-flightline` elements somehow have `display: flex`, and
3. Those `auro-flightline` elements needs to have `width:100%` (or else they will disappear as per the 'disappearing' issue).
```
<auro-flight flights='["AS 1436"]'>
  <div style="display: flex">
    <auro-flightline style="width: 100%"></auro-flightline>
    <auro-flightline style="width: 100%">
      <auro-flight-segment></auro-flight-segment>
    </auro-flightline>
  </div>
</auro-flight>
```

Since I'm going outside of the given instructions, please advise if I should not go into / just ignore this approach.

**Comment by blackfalcon** [comment]
We're able to troubleshoot this issue and discovered what the root cause of the issue is. 

<img width="1002" alt="Screen Shot 2023-07-26 at 10 29 04 AM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/181089/8b70a3c7-11da-438e-ad10-a7912c113722">

As seen in the screenshot. when there is a `nonstop` property on the node that contains a layover, this causes the UI to break. The `nonstop` property is ONLY to be used when there are no layovers listed for the flight. 

@ggrewal108 will look into the data for this scenario with the intent to understand why flights in her list that clearly have layovers are also being tagged as nonstop flights. 

The code for nonstop and layovers were never engineered to account for both being used at the same time. 

https://github.com/AlaskaAirlines/auro-flightline/blob/63ed29d5214f48ee8de092b2c5d088ab98f969ba/src/style-flightline.scss#L22-L40

**Comment by ggrewal108** [comment]
> We're able to troubleshoot this issue and discovered what the root cause of the issue is.
> 
> <img alt="Screen Shot 2023-07-26 at 10 29 04 AM" width="1002" src="https://user-images.githubusercontent.com/181089/256315577-8b70a3c7-11da-438e-ad10-a7912c113722.png">
> As seen in the screenshot. when there is a `nonstop` property on the node that contains a layover, this causes the UI to break. The `nonstop` property is ONLY to be used when there are no layovers listed for the flight.
> 
> @ggrewal108 will look into the data for this scenario with the intent to understand why flights in her list that clearly have layovers are also being tagged as nonstop flights.
> 
> The code for nonstop and layovers were never engineered to account for both being used at the same time.
> 
> https://github.com/AlaskaAirlines/auro-flightline/blob/63ed29d5214f48ee8de092b2c5d088ab98f969ba/src/style-flightline.scss#L22-L40

@blackfalcon Thanks for taking the time to meet me and to go over this issue today. Given the complexity of the issue, I believe it’s going to take me more than a cursory glance to understand what going on underneath the hood and to give this issue the consideration that it deserves. However, at the moment there are other items that require my attention and consideration, therefore I am going to put this on hold and will try to address it at the earliest opportunity possible. Once again, than you for your understanding and your collaboration.

**Comment by blackfalcon** [comment]
@ggrewal108 no worries. I am curious why this `nonstop` CSS selector is being added to the DOM at render. The code for how this works is all based on children within the node. 

https://github.com/AlaskaAirlines/auro-flightline/blob/63ed29d5214f48ee8de092b2c5d088ab98f969ba/src/auro-flightline.js#L98-L105

Basically, if there are no children in that slot, then you get the `nonstop` selector added. If there is `1`, then nothing is added, if there is `> 1` then you get the `multiple` selector. 

By adding things to the DOM, I can't get this to reproduce. There has to be an answer in the data that is rendering the UI on your end.

**Comment by ggrewal108** [comment]
> @ggrewal108 no worries. I am curious why this `nonstop` CSS selector is being added to the DOM at render. The code for how this works is all based on children within the node.
> 
> https://github.com/AlaskaAirlines/auro-flightline/blob/63ed29d5214f48ee8de092b2c5d088ab98f969ba/src/auro-flightline.js#L98-L105
> 
> Basically, if there are no children in that slot, then you get the `nonstop` selector added. If there is `1`, then nothing is added, if there is `> 1` then you get the `multiple` selector.
> 
> By adding things to the DOM, I can't get this to reproduce. There has to be an answer in the data that is rendering the UI on your end.
<img width="1728" alt="Screenshot 2023-07-28 at 2 03 21 PM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/107504325/b0390f50-5a66-498a-844e-f73215e756b3">
This array is the data that is supplied to the component that renders the flight line and the flight segments. The flight line is always set to render, however, the segments only render when the array that is received has length > 1. In the case where the array is empty, the <auro-flightline> component is never rendered. When the length is > 1, the destination property is used for iata. 
I have noticed that when the flight option is initially nonstop but then sorted and the new sorted option has flight segments, thats when the distortion happens. However, the data supplied still seems to be right.
<img width="980" alt="Screenshot 2023-07-28 at 3 02 24 PM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/107504325/0f20f7dc-0482-490e-be5d-79a34ce63c21">
<img width="1727" alt="Screenshot 2023-07-28 at 3 03 27 PM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/107504325/c8abc585-abb9-4462-8401-92ffffeed0dd">
Could this possibly be a react problem? I don't believe the problem is necessarily with the data that is supplied to the components.

**Comment by blackfalcon** [comment]
@ggrewal108 this all makes sense. 

>  flight option is initially nonstop but then sorted and the new sorted option has flight segments

That's the smoking gun right there. The `nonstop` selector is being added because at render the segment is >1. But what you are saying is that post resort the segments are >1, the component is NOT rendering, and that `nonstop` selector is still there. 

Why is the segment being added AFTER the resort?

**Comment by tjgrist** [comment]
We ended up adding a React key to each auro-flightline element, and that resolved the issue. 
<img width="570" alt="Screenshot 2023-08-08 at 9 56 30 AM" src="https://github.com/AlaskaAirlines/auro-flightline/assets/17755678/7b7a1c9a-61f9-4286-af01-c76c80530ff4">

**Comment by blackfalcon** [comment]
@tjgrist can you provide a reason why this is happening and/or why someone has to use this with this component? 

I'd like to get this added to the install docs as a reference for future users of the element. This appears to be a React'ism as we have not run into this with the Svelte teams.

**Comment by ggrewal108** [comment]
> @tjgrist can you provide a reason why this is happening and/or why someone has to use this with this component?
> 
> I'd like to get this added to the install docs as a reference for future users of the element. This appears to be a React'ism as we have not run into this with the Svelte teams.
<img width="653" alt="MicrosoftTeams-image" src="https://github.com/AlaskaAirlines/auro-flightline/assets/107504325/d969bbfe-8772-4715-b0f7-8e00d524befd">
React needs a key to be able to differentiate among all the rendered auro-flightlines or more generically when you render multiples of the same component. It uses that key to determine which component/element needs to be rendered and how much of it needs to be rendered. Since we weren't providing the flight line with the key, it didn't seem to be rendering it from scratch again, therefore, the css in the shadow root wasn't getting updated correctly - It was only updating the stuff it needed to update which were the other things in that component.

**Comment by tjgrist** [comment]
Literally couldn't have said it better myself

**Comment by blackfalcon** [comment]
See commit 

- https://github.com/AlaskaAirlines/auro-flightline/commit/550479ca97e9b7e5374df977abd9d48dbd516657
